my_app_pfe_homepage:
    path:     /
    defaults: { _controller: MyAppPfeBundle:Default:index }
AffichageAction:
    path:     /page
    defaults: { _controller: MyAppPfeBundle:Aeroport:affichage }

detailsAction:
    path:     /details
    defaults: { _controller: MyAppPfeBundle:Aeroport:details }
AjoutAction:
        path:     /ajout
        defaults: { _controller: MyAppPfeBundle:Aeroport:Ajout }

deleteAction:
        path:     /supprimer/{code}
        defaults: { _controller: MyAppPfeBundle:Aeroport:delete }

updateAction:
        path:     /update/{code}
        defaults: { _controller: MyAppPfeBundle:Aeroports:update }